/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layouts
         * @description 下发布局定义。
         *
         *     前端本可直接读 shared/ 下的同一批文件，这个接口的作用是让两端
         *     在运行时校验读到的是同一份数据，也让 OpenAPI 里带上布局的类型定义。
         */
        get: operations["list_layouts_api_v1_design_layouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_api_v1_design_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Deck */
        get: operations["get_sample_deck_api_v1_design_sample_deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Deck Issues */
        get: operations["get_sample_deck_issues_api_v1_design_sample_deck_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck/pptx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Sample Deck */
        get: operations["export_sample_deck_api_v1_design_sample_deck_pptx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulletsBlock */
        BulletsBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bullets";
            /** Items */
            items: string[];
        };
        /** ChartBlock */
        ChartBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chart";
            /**
             * Chart Type
             * @enum {string}
             */
            chart_type: "bar" | "column" | "line" | "pie";
            /** Categories */
            categories: string[];
            /** Series */
            series: components["schemas"]["ChartSeries"][];
            /** Unit */
            unit?: string | null;
        };
        /** ChartSeries */
        ChartSeries: {
            /** Name */
            name: string;
            /** Values */
            values: number[];
        };
        /**
         * Deck
         * @description 演示文稿的统一内容模型。
         *
         *     内容、布局、主题三者分离：这里只描述"有什么内容、放在哪个槽位"，
         *     槽位几何来自布局，视觉表现来自主题。
         */
        Deck: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Theme Id */
            theme_id: string;
            /** Slides */
            slides: components["schemas"]["Slide"][];
        };
        /**
         * Decoration
         * @description 纯装饰图形，不承载内容，两端渲染器按同一份声明绘制
         */
        Decoration: {
            /**
             * Type
             * @enum {string}
             */
            type: "rule" | "block";
            rect: components["schemas"]["Rect"];
            /** Color */
            color: string;
        };
        /**
         * FontFamily
         * @description Web 与 PPTX 分别声明字体名。
         *
         *     浏览器可用 webfont，而 PPTX 只能引用观众机器上已安装的字体，
         *     两者无法统一，因此显式分开声明，而不是让某一端将就另一端。
         */
        FontFamily: {
            /** Web */
            web: string;
            /** Pptx Latin */
            pptx_latin: string;
            /** Pptx East Asian */
            pptx_east_asian: string;
        };
        /** Fonts */
        Fonts: {
            display: components["schemas"]["FontFamily"];
            body: components["schemas"]["FontFamily"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 显式声明响应模型，让 OpenAPI 产出带字段的 schema。
         *     前端类型由 OpenAPI 生成，接口若只返回裸 dict，生成结果会退化为 object。
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "down";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "down";
        };
        /** ImageBlock */
        ImageBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Url */
            url?: string | null;
            /** Alt */
            alt: string;
            /**
             * Source
             * @enum {string}
             */
            source: "generated" | "stock" | "upload" | "placeholder";
        };
        /** KpiBlock */
        KpiBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "kpi";
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /** Layout */
        Layout: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Usage */
            usage: string;
            /** Slots */
            slots: components["schemas"]["Slot"][];
            /**
             * Decorations
             * @default []
             */
            decorations: components["schemas"]["Decoration"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Palette */
        Palette: {
            /** Background */
            background: string;
            /** Surface */
            surface: string;
            /** Ink */
            ink: string;
            /** Ink Soft */
            ink_soft: string;
            /** Ink Muted */
            ink_muted: string;
            /** Accent */
            accent: string;
            /** Accent Soft */
            accent_soft: string;
            /** Line */
            line: string;
            /** Line Strong */
            line_strong: string;
            /** Chart Series */
            chart_series: string[];
        };
        /**
         * Rect
         * @description 归一化矩形，取值 0–1，相对基准画布。
         *
         *     用归一化而非绝对坐标，是为了让缩略图、全屏预览和导出三者
         *     共用同一份几何定义，换算只发生在各自的渲染边界上。
         */
        Rect: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Shape */
        Shape: {
            /** Radius Pt */
            radius_pt: number;
            /** Border Width Pt */
            border_width_pt: number;
            /**
             * Bullet Marker
             * @enum {string}
             */
            bullet_marker: "rule" | "dot" | "index";
        };
        /** Slide */
        Slide: {
            /** Id */
            id: string;
            /** Layout Id */
            layout_id: string;
            /** Blocks */
            blocks: (components["schemas"]["TextBlock"] | components["schemas"]["BulletsBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["ChartBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["KpiBlock"])[];
            /** Speaker Notes */
            speaker_notes?: string | null;
            /**
             * Revision
             * @default 1
             */
            revision: number;
        };
        /** Slot */
        Slot: {
            /** Id */
            id: string;
            /** Accepts */
            accepts: ("text" | "bullets" | "image" | "chart" | "table" | "kpi")[];
            rect: components["schemas"]["Rect"];
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Text Style */
            text_style?: ("display" | "title" | "subtitle" | "body" | "bullet" | "caption" | "kpi_value" | "kpi_label" | "kpi_note" | "table_header" | "table_cell" | "chart_label") | null;
            /** @default {} */
            capacity: components["schemas"]["SlotCapacity"];
        };
        /**
         * SlotCapacity
         * @description 布局对内容长度的声明式约束。
         *
         *     它有两个用途：作为提示词里的硬指标约束模型生成长度，
         *     以及在字体度量之前做一次廉价的快速筛查。
         *     最终是否溢出仍以真实字体度量为准。
         */
        SlotCapacity: {
            /** Max Lines */
            max_lines?: number | null;
            /** Max Chars */
            max_chars?: number | null;
            /** Max Items */
            max_items?: number | null;
            /** Max Chars Per Item */
            max_chars_per_item?: number | null;
            /** Max Rows */
            max_rows?: number | null;
            /** Max Columns */
            max_columns?: number | null;
            /** Max Chars Per Cell */
            max_chars_per_cell?: number | null;
        };
        /**
         * StructureIssue
         * @description 结构问题。
         *
         *     error 表示内容与布局的契约被破坏，必须阻断导出；
         *     warning 表示内容偏长可能观感不佳，允许继续。
         */
        StructureIssue: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Slide Id */
            slide_id: string;
            /** Slot Id */
            slot_id: string | null;
            /** Message */
            message: string;
        };
        /** TableBlock */
        TableBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Header */
            header: string[];
            /** Rows */
            rows: string[][];
        };
        /** TextBlock */
        TextBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** TextStyle */
        TextStyle: {
            /**
             * Font
             * @enum {string}
             */
            font: "display" | "body";
            /** Size Pt */
            size_pt: number;
            /** Line Height */
            line_height: number;
            /** Weight */
            weight: number;
            /** Letter Spacing Pt */
            letter_spacing_pt: number;
            /**
             * Color
             * @enum {string}
             */
            color: "background" | "surface" | "ink" | "ink_soft" | "ink_muted" | "accent" | "accent_soft" | "line" | "line_strong";
        };
        /** Theme */
        Theme: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            palette: components["schemas"]["Palette"];
            fonts: components["schemas"]["Fonts"];
            /** Text Styles */
            text_styles: {
                [key: string]: components["schemas"]["TextStyle"];
            };
            shape: components["schemas"]["Shape"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserPublic"];
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    list_layouts_api_v1_design_layouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"][];
                };
            };
        };
    };
    list_themes_api_v1_design_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"][];
                };
            };
        };
    };
    get_sample_deck_api_v1_design_sample_deck_get: {
        parameters: {
            query?: {
                theme_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_deck_issues_api_v1_design_sample_deck_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureIssue"][];
                };
            };
        };
    };
    export_sample_deck_api_v1_design_sample_deck_pptx_get: {
        parameters: {
            query?: {
                theme_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
