/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layouts
         * @description 下发布局定义。
         *
         *     前端本可直接读 shared/ 下的同一批文件，这个接口的作用是让两端
         *     在运行时校验读到的是同一份数据，也让 OpenAPI 里带上布局的类型定义。
         */
        get: operations["list_layouts_api_v1_design_layouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_api_v1_design_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Deck */
        get: operations["get_sample_deck_api_v1_design_sample_deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Deck Issues */
        get: operations["get_sample_deck_issues_api_v1_design_sample_deck_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/sample-deck/pptx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Sample Deck */
        get: operations["export_sample_deck_api_v1_design_sample_deck_pptx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Remove Project */
        delete: operations["remove_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Source */
        post: operations["create_text_source_api_v1_projects__project_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source_api_v1_projects__project_id__sources_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Source */
        delete: operations["remove_source_api_v1_projects__project_id__sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outline */
        get: operations["get_outline_api_v1_projects__project_id__outline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Outline */
        patch: operations["update_outline_api_v1_projects__project_id__outline_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Outline */
        post: operations["generate_outline_api_v1_projects__project_id__outline_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Outline */
        post: operations["confirm_outline_api_v1_projects__project_id__outline_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/unconfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unconfirm Outline */
        post: operations["unconfirm_outline_api_v1_projects__project_id__outline_unconfirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Outline Events */
        get: operations["stream_outline_events_api_v1_projects__project_id__outline_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["get_deck_api_v1_projects__project_id__deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Deck */
        post: operations["generate_deck_api_v1_projects__project_id__deck_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/{slide_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Slide */
        post: operations["retry_slide_api_v1_projects__project_id__deck_slides__slide_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Deck */
        post: operations["cancel_deck_api_v1_projects__project_id__deck_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/{slide_id}/blocks/{block_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Slide Image */
        put: operations["replace_slide_image_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__image_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/{slide_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Slide Block */
        patch: operations["update_slide_block_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Slides */
        put: operations["reorder_slides_api_v1_projects__project_id__deck_slides_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/{slide_id}/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Slide Layouts */
        get: operations["list_slide_layouts_api_v1_projects__project_id__deck_slides__slide_id__layouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/slides/{slide_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Switch Slide Layout */
        put: operations["switch_slide_layout_api_v1_projects__project_id__deck_slides__slide_id__layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/deck/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Deck Events */
        get: operations["stream_deck_events_api_v1_projects__project_id__deck_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media */
        get: operations["get_media_api_v1_media__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_replace_slide_image_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__image_put */
        Body_replace_slide_image_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__image_put: {
            /** File */
            file: string;
            /** Revision */
            revision: number;
        };
        /** Body_upload_source_api_v1_projects__project_id__sources_upload_post */
        Body_upload_source_api_v1_projects__project_id__sources_upload_post: {
            /** File */
            file: string;
        };
        /** BulletsBlock */
        BulletsBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bullets";
            /** Items */
            items: string[];
        };
        /** BulletsBlockUpdate */
        BulletsBlockUpdate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bullets";
            /** Revision */
            revision: number;
            /** Items */
            items: string[];
        };
        /** ChartBlock */
        ChartBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "chart";
            /**
             * Chart Type
             * @enum {string}
             */
            chart_type: "bar" | "column" | "line" | "pie";
            /** Categories */
            categories: string[];
            /** Series */
            series: components["schemas"]["ChartSeries"][];
            /** Unit */
            unit?: string | null;
        };
        /** ChartSeries */
        ChartSeries: {
            /** Name */
            name: string;
            /** Values */
            values: number[];
        };
        /**
         * Deck
         * @description PPT 的统一内容模型。
         *
         *     内容、布局、主题三者分离：这里只描述"有什么内容、放在哪个槽位"，
         *     槽位几何来自布局，视觉表现来自主题。
         */
        Deck: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Theme Id */
            theme_id: string;
            /** Slides */
            slides: components["schemas"]["Slide"][];
        };
        /** DeckGenerateAccepted */
        DeckGenerateAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default generating
             * @constant
             */
            status: "generating";
            /** Total */
            total: number;
            /** Pending */
            pending: number;
        };
        /** DeckGenerateRequest */
        DeckGenerateRequest: {
            /**
             * Regenerate All
             * @default false
             */
            regenerate_all: boolean;
        };
        /** DeckPublic */
        DeckPublic: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /** Theme Id */
            theme_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "generating" | "ready" | "partial";
            /** Total */
            total: number;
            /** Ready */
            ready: number;
            /** Failed */
            failed: number;
            /** Slides */
            slides: components["schemas"]["SlidePublic"][];
        };
        /**
         * Decoration
         * @description 纯装饰图形，不承载内容，两端渲染器按同一份声明绘制
         */
        Decoration: {
            /**
             * Type
             * @enum {string}
             */
            type: "rule" | "block";
            rect: components["schemas"]["Rect"];
            /** Color */
            color: string;
        };
        /**
         * FontFamily
         * @description Web 与 PPTX 分别声明字体名。
         *
         *     浏览器可用 webfont，而 PPTX 只能引用观众机器上已安装的字体，
         *     两者无法统一，因此显式分开声明，而不是让某一端将就另一端。
         */
        FontFamily: {
            /** Web */
            web: string;
            /** Pptx Latin */
            pptx_latin: string;
            /** Pptx East Asian */
            pptx_east_asian: string;
        };
        /** Fonts */
        Fonts: {
            display: components["schemas"]["FontFamily"];
            body: components["schemas"]["FontFamily"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 显式声明响应模型，让 OpenAPI 产出带字段的 schema。
         *     前端类型由 OpenAPI 生成，接口若只返回裸 dict，生成结果会退化为 object。
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "down";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "down";
        };
        /** ImageBlock */
        ImageBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Url */
            url?: string | null;
            /** Alt */
            alt: string;
            /**
             * Source
             * @enum {string}
             */
            source: "generated" | "stock" | "upload" | "placeholder";
            /** Credit */
            credit?: string | null;
        };
        /** KpiBlock */
        KpiBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "kpi";
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /** KpiBlockUpdate */
        KpiBlockUpdate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "kpi";
            /** Revision */
            revision: number;
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /** Layout */
        Layout: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Usage */
            usage: string;
            /** Slots */
            slots: components["schemas"]["Slot"][];
            /**
             * Decorations
             * @default []
             */
            decorations: components["schemas"]["Decoration"][];
        };
        /** LayoutCandidatePublic */
        LayoutCandidatePublic: {
            /** Layout Id */
            layout_id: string;
            /** Name */
            name: string;
            /** Usage */
            usage: string;
            /** Compatible */
            compatible: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Current
             * @default false
             */
            current: boolean;
        };
        /** LayoutSwitchRequest */
        LayoutSwitchRequest: {
            /** Layout Id */
            layout_id: string;
            /** Revision */
            revision: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OutlineGenerateAccepted */
        OutlineGenerateAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default generating
             * @constant
             */
            status: "generating";
        };
        /** OutlinePage */
        OutlinePage: {
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /** Key Points */
            key_points: string[];
            /** Source Refs */
            source_refs?: string[];
            /** Layout Id */
            layout_id: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
        };
        /** OutlinePublic */
        OutlinePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "generating" | "draft" | "confirmed" | "failed";
            /** Pages */
            pages: components["schemas"]["OutlinePage"][];
            /** Revision */
            revision: number;
            /** Job Id */
            job_id: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OutlineRevisionRequest */
        OutlineRevisionRequest: {
            /** Revision */
            revision: number;
        };
        /** OutlineUpdate */
        OutlineUpdate: {
            /** Revision */
            revision: number;
            /** Pages */
            pages: components["schemas"]["OutlinePage"][];
        };
        /** Palette */
        Palette: {
            /** Background */
            background: string;
            /** Surface */
            surface: string;
            /** Ink */
            ink: string;
            /** Ink Soft */
            ink_soft: string;
            /** Ink Muted */
            ink_muted: string;
            /** Accent */
            accent: string;
            /** Accent Soft */
            accent_soft: string;
            /** Line */
            line: string;
            /** Line Strong */
            line_strong: string;
            /** Chart Series */
            chart_series: string[];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Audience */
            audience?: string | null;
            /**
             * Tone
             * @default professional
             * @enum {string}
             */
            tone: "professional" | "plain" | "punchy";
            /**
             * Page Count
             * @default 10
             */
            page_count: number;
            /**
             * Theme Id
             * @default ivory
             */
            theme_id: string;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Audience */
            audience: string | null;
            /**
             * Tone
             * @enum {string}
             */
            tone: "professional" | "plain" | "punchy";
            /** Page Count */
            page_count: number;
            /** Theme Id */
            theme_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "outline_ready" | "generating" | "ready";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sources */
            sources: components["schemas"]["SourcePublic"][];
        };
        /** ProjectPublic */
        ProjectPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Audience */
            audience: string | null;
            /**
             * Tone
             * @enum {string}
             */
            tone: "professional" | "plain" | "punchy";
            /** Page Count */
            page_count: number;
            /** Theme Id */
            theme_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "outline_ready" | "generating" | "ready";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Audience */
            audience?: string | null;
            /** Tone */
            tone?: ("professional" | "plain" | "punchy") | null;
            /** Page Count */
            page_count?: number | null;
            /** Theme Id */
            theme_id?: string | null;
        };
        /**
         * Rect
         * @description 归一化矩形，取值 0–1，相对基准画布。
         *
         *     用归一化而非绝对坐标，是为了让缩略图、全屏预览和导出三者
         *     共用同一份几何定义，换算只发生在各自的渲染边界上。
         */
        Rect: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Shape */
        Shape: {
            /** Radius Pt */
            radius_pt: number;
            /** Border Width Pt */
            border_width_pt: number;
            /**
             * Bullet Marker
             * @enum {string}
             */
            bullet_marker: "rule" | "dot" | "index";
        };
        /** Slide */
        Slide: {
            /** Id */
            id: string;
            /** Layout Id */
            layout_id: string;
            /** Blocks */
            blocks: (components["schemas"]["TextBlock"] | components["schemas"]["BulletsBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["ChartBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["KpiBlock"])[];
            /** Speaker Notes */
            speaker_notes?: string | null;
            /**
             * Revision
             * @default 1
             */
            revision: number;
        };
        /** SlideOrderRequest */
        SlideOrderRequest: {
            /** Slide Ids */
            slide_ids: string[];
        };
        /** SlidePublic */
        SlidePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Outline Page Id
             * Format: uuid
             */
            outline_page_id: string;
            /** Position */
            position: number;
            /** Layout Id */
            layout_id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "generating" | "ready" | "failed";
            /** Blocks */
            blocks: (components["schemas"]["TextBlock"] | components["schemas"]["BulletsBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["ChartBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["KpiBlock"])[];
            /** Speaker Notes */
            speaker_notes: string | null;
            /** Issues */
            issues: components["schemas"]["StructureIssue"][];
            /** Error */
            error: string | null;
            /** Revision */
            revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Slot */
        Slot: {
            /** Id */
            id: string;
            /** Accepts */
            accepts: ("text" | "bullets" | "image" | "chart" | "table" | "kpi")[];
            rect: components["schemas"]["Rect"];
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Text Style */
            text_style?: ("display" | "title" | "subtitle" | "body" | "bullet" | "caption" | "kpi_value" | "kpi_label" | "kpi_note" | "table_header" | "table_cell" | "chart_label") | null;
            /** @default {} */
            capacity: components["schemas"]["SlotCapacity"];
        };
        /**
         * SlotCapacity
         * @description 布局对内容长度的声明式约束。
         *
         *     它有两个用途：作为提示词里的硬指标约束模型生成长度，
         *     以及在字体度量之前做一次廉价的快速筛查。
         *     最终是否溢出仍以真实字体度量为准。
         */
        SlotCapacity: {
            /** Max Lines */
            max_lines?: number | null;
            /** Max Chars */
            max_chars?: number | null;
            /** Max Items */
            max_items?: number | null;
            /** Max Chars Per Item */
            max_chars_per_item?: number | null;
            /** Max Rows */
            max_rows?: number | null;
            /** Max Columns */
            max_columns?: number | null;
            /** Max Chars Per Cell */
            max_chars_per_cell?: number | null;
            /** Max Series */
            max_series?: number | null;
            /** Max Categories */
            max_categories?: number | null;
        };
        /** SourcePublic */
        SourcePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "topic" | "text" | "document";
            /** Filename */
            filename: string | null;
            /** Content Type */
            content_type: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Sections */
            sections: components["schemas"]["SourceSection"][];
            /** Warnings */
            warnings: string[];
            /** Char Count */
            char_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceSection
         * @description 输入材料的一个小节。
         *
         *     保留标题层级而非拍平成纯文本，是因为大纲规划本质上是结构提炼：
         *     原文档已有的结构信息如果丢掉，等于让模型再猜一遍。
         */
        SourceSection: {
            /** Level */
            level: number;
            /** Heading */
            heading?: string | null;
            /** Text */
            text: string;
            /** Locator */
            locator: string;
        };
        /**
         * StructureIssue
         * @description 结构问题。
         *
         *     error 表示内容与布局的契约被破坏，必须阻断导出；
         *     warning 表示内容偏长可能观感不佳，允许继续。
         */
        StructureIssue: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            /** Slide Id */
            slide_id: string;
            /** Slot Id */
            slot_id: string | null;
            /** Message */
            message: string;
        };
        /** TableBlock */
        TableBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Header */
            header: string[];
            /** Rows */
            rows: string[][];
        };
        /** TableBlockUpdate */
        TableBlockUpdate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
            /** Revision */
            revision: number;
            /** Header */
            header: string[];
            /** Rows */
            rows: string[][];
        };
        /** TextBlock */
        TextBlock: {
            /** Id */
            id: string;
            /** Slot Id */
            slot_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** TextBlockUpdate */
        TextBlockUpdate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Revision */
            revision: number;
            /** Text */
            text: string;
        };
        /** TextSourceCreate */
        TextSourceCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "topic" | "text";
            /** Content */
            content: string;
        };
        /** TextStyle */
        TextStyle: {
            /**
             * Font
             * @enum {string}
             */
            font: "display" | "body";
            /** Size Pt */
            size_pt: number;
            /** Line Height */
            line_height: number;
            /** Weight */
            weight: number;
            /** Letter Spacing Pt */
            letter_spacing_pt: number;
            /**
             * Color
             * @enum {string}
             */
            color: "background" | "surface" | "ink" | "ink_soft" | "ink_muted" | "accent" | "accent_soft" | "line" | "line_strong";
        };
        /** Theme */
        Theme: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            palette: components["schemas"]["Palette"];
            fonts: components["schemas"]["Fonts"];
            /** Text Styles */
            text_styles: {
                [key: string]: components["schemas"]["TextStyle"];
            };
            shape: components["schemas"]["Shape"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserPublic"];
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    list_layouts_api_v1_design_layouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"][];
                };
            };
        };
    };
    list_themes_api_v1_design_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"][];
                };
            };
        };
    };
    get_sample_deck_api_v1_design_sample_deck_get: {
        parameters: {
            query?: {
                theme_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_deck_issues_api_v1_design_sample_deck_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureIssue"][];
                };
            };
        };
    };
    export_sample_deck_api_v1_design_sample_deck_pptx_get: {
        parameters: {
            query?: {
                theme_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPublic"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_text_source_api_v1_projects__project_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_v1_projects__project_id__sources_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_projects__project_id__sources_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_source_api_v1_projects__project_id__sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outline_api_v1_projects__project_id__outline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlinePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_outline_api_v1_projects__project_id__outline_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlinePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_outline_api_v1_projects__project_id__outline_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineGenerateAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_outline_api_v1_projects__project_id__outline_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlinePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unconfirm_outline_api_v1_projects__project_id__outline_unconfirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlinePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_outline_events_api_v1_projects__project_id__outline_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deck_api_v1_projects__project_id__deck_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_deck_api_v1_projects__project_id__deck_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckGenerateAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_slide_api_v1_projects__project_id__deck_slides__slide_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckGenerateAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_deck_api_v1_projects__project_id__deck_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_slide_image_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__image_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                block_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_slide_image_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__image_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlidePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_slide_block_api_v1_projects__project_id__deck_slides__slide_id__blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                block_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextBlockUpdate"] | components["schemas"]["BulletsBlockUpdate"] | components["schemas"]["KpiBlockUpdate"] | components["schemas"]["TableBlockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlidePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_slides_api_v1_projects__project_id__deck_slides_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlideOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlidePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slide_layouts_api_v1_projects__project_id__deck_slides__slide_id__layouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutCandidatePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_slide_layout_api_v1_projects__project_id__deck_slides__slide_id__layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlidePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_deck_events_api_v1_projects__project_id__deck_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_api_v1_media__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
