"""add_progress_to_image_projects

Revision ID: 19281ca55db6
Revises: ae1226a22904
Create Date: 2026-09-03 14:46:27.840715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19281ca55db6'
down_revision: Union[str, Sequence[str], None] = 'ae1226a22904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_projects', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_image_projects_job_id'), table_name='image_projects', postgresql_where='(job_id IS NOT NULL)')
    op.create_index(op.f('ix_image_projects_user_id'), 'image_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_projects_user_id'), table_name='image_projects')
    op.create_index(op.f('ix_image_projects_job_id'), 'image_projects', ['job_id'], unique=False, postgresql_where='(job_id IS NOT NULL)')
    op.drop_column('image_projects', 'progress')
    # ### end Alembic commands ###
