"""track outline input signature

Revision ID: 65507fe6fb52
Revises: 457830d59f00
Create Date: 2026-08-05 14:25:50.932598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65507fe6fb52"
down_revision: str | Sequence[str] | None = "457830d59f00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_outlines", sa.Column("input_signature", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_outlines", "input_signature")
    # ### end Alembic commands ###
