"""create_image_projects

Revision ID: ae1226a22904
Revises: e5f6a7b8c9d0
Create Date: 2026-09-03 11:42:15.508518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1226a22904'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=64), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=5), nullable=False),
    sa.Column('optimized_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_projects_user_created', 'image_projects', ['user_id', 'created_at'], unique=False)
    # Worker 幂等查找：只索引非空 job_id，避免全表扫描
    op.create_index(
        'ix_image_projects_job_id',
        'image_projects',
        ['job_id'],
        postgresql_where=sa.text('job_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_projects_job_id', table_name='image_projects')
    op.drop_index(op.f('ix_image_projects_user_id'), table_name='image_projects')
    op.drop_index('ix_image_projects_user_created', table_name='image_projects')
    op.drop_table('image_projects')
    # ### end Alembic commands ###
